---
freeipa_controller_default_enabled: false
freeipa_controller_default_vendor_package_strategy: overlay-managed
freeipa_controller_default_realm: EXAMPLE.INTERNAL
freeipa_controller_default_domain: example.internal
freeipa_controller_default_server_hostname: ipa01.example.internal
freeipa_controller_default_server_ip_address: ""
freeipa_controller_default_ds_instance_name: example-internal
freeipa_controller_default_organization: Example Infrastructure
freeipa_controller_default_subject_base: O=Example Infrastructure
freeipa_controller_default_ca_subject_base: O=Example Infrastructure
freeipa_controller_default_admin_user: admin
freeipa_controller_default_directory_manager_user: directory-manager
freeipa_controller_default_enable_dns: false
freeipa_controller_default_enable_ca: true
freeipa_controller_default_enable_pkinit: true
freeipa_controller_default_enable_kra: false
freeipa_controller_default_smartcard_enabled: true
freeipa_controller_default_manage_hosts_file: true
freeipa_controller_default_idrange_start: 200000
freeipa_controller_default_idrange_size: 200000
freeipa_controller_default_overlay_repo_name: freeipa-overlay
freeipa_controller_default_extra_packages: []
