---
all:
  children:
    install_targets:
      hosts:
        target_system_remote:
          ansible_host: 10.9.8.90
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    qemu_hypervisors:
      hosts:
        qemu_control_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    binpkg_repositories:
      hosts:
        vm_binpkg_repository:
          ansible_host: 10.9.8.90
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
