---
zpool_name: rpool
zpool_compatibility: 'off'
zpool_altroot: "{{ install_target_root }}"
zfs_pool_properties:
  ashift: '12'
  autotrim: 'on'
  compatibility: "{{ zpool_compatibility }}"
zfs_fs_properties:
  acltype: 'posixacl'
  compression: 'zstd'
  dnodesize: 'auto'
  relatime: 'on'
  xattr: 'sa'
  mountpoint: 'none'
zfs_root_datasets:
  - { name: "{{ zpool_name }}/ROOT", extra: "-o mountpoint=none -o canmount=off" }
  - { name: "{{ zpool_name }}/ROOT/gentoo", extra: "-o mountpoint=/ -o canmount=noauto" }
  - { name: "{{ zpool_name }}/home", extra: "-o mountpoint=/home" }
  - { name: "{{ zpool_name }}/opt", extra: "-o mountpoint=/opt" }
  - { name: "{{ zpool_name }}/srv", extra: "-o mountpoint=/srv" }
  - { name: "{{ zpool_name }}/tmp", extra: "-o mountpoint=/tmp -o setuid=off" }
  - { name: "{{ zpool_name }}/usr", extra: "-o mountpoint=/usr -o canmount=off" }
  - { name: "{{ zpool_name }}/usr/local", extra: "-o mountpoint=/usr/local" }
  - { name: "{{ zpool_name }}/var", extra: "-o mountpoint=/var -o canmount=off" }
  - { name: "{{ zpool_name }}/var/log", extra: "-o mountpoint=/var/log" }
  - { name: "{{ zpool_name }}/var/lib", extra: "-o mountpoint=/var/lib" }
zfs_boot_pool_name: bpool
zfs_boot_pool_properties:
  ashift: '12'
  autotrim: 'on'
  compatibility: "{{ zpool_compatibility }}"
zfs_boot_fs_properties:
  acltype: 'posixacl'
  compression: 'zstd'
  dnodesize: 'auto'
  relatime: 'on'
  xattr: 'sa'
  mountpoint: 'none'
zfs_boot_datasets:
  - { name: "{{ zfs_boot_pool_name }}/BOOT", extra: "-o mountpoint=none -o canmount=off" }
  - { name: "{{ zfs_boot_pool_name }}/BOOT/gentoo", extra: "-o mountpoint=/boot" }
zfs_boot_pool_devices: []
zfs_root_pool_devices: []
