---
telemetry_collectd_default_enabled: false
telemetry_collectd_default_hostname: "{{ inventory_hostname | default('stage5-host') }}"
telemetry_collectd_default_interval: 10
telemetry_collectd_default_read_threads: 5
telemetry_collectd_default_write_threads: 5
telemetry_collectd_default_base_dir: /var/lib/collectd
telemetry_collectd_default_plugin_dir: /usr/lib64/collectd
telemetry_collectd_default_include_dir: /etc/collectd.d
telemetry_collectd_default_network_listen: false
telemetry_collectd_default_network_listen_host: "0.0.0.0"
telemetry_collectd_default_network_listen_port: 25826
telemetry_collectd_default_network_servers: []
telemetry_collectd_default_write_graphite_enabled: false
telemetry_collectd_default_write_graphite_host: 127.0.0.1
telemetry_collectd_default_write_graphite_port: 2003
telemetry_collectd_default_write_graphite_prefix: collectd.
telemetry_collectd_default_write_prometheus_enabled: false
telemetry_collectd_default_write_prometheus_host: "0.0.0.0"
telemetry_collectd_default_write_prometheus_port: 9103
telemetry_collectd_default_plugins:
  - cpu
  - df
  - disk
  - entropy
  - interface
  - load
  - memory
  - nfs
  - processes
  - protocols
  - swap
  - tcpconns
  - uptime
