---
dns_hetzner_cloud_api_endpoint: https://api.hetzner.cloud/v1
dns_hetzner_cloud_provider: hetzner_cloud_dns

dns_hetzner_cloud_change_policy:
  source_of_truth: netbox
  default_ttl: 300
  apply: false
  allow_delete: false

dns_hetzner_cloud_token_groups:
  - name: rfc1918
    token_name: "{{ vault_hetzner_dns_rfc1918_token_name | default('') }}"
    api_token: "{{ vault_hetzner_dns_rfc1918_api_token | default('') }}"
    zones: "{{ vault_hetzner_dns_rfc1918_zones | default([]) }}"
  - name: vernetzen
    token_name: "{{ vault_hetzner_dns_vernetzen_token_name | default('') }}"
    api_token: "{{ vault_hetzner_dns_vernetzen_api_token | default('') }}"
    zones: "{{ vault_hetzner_dns_vernetzen_zones | default([]) }}"
  - name: yukon
    token_name: "{{ vault_hetzner_dns_yukon_token_name | default('') }}"
    api_token: "{{ vault_hetzner_dns_yukon_api_token | default('') }}"
    zones: "{{ vault_hetzner_dns_yukon_zones | default([]) }}"

dns_hetzner_cloud_zone_groups:
  - name: rfc1918
    zones: "{{ vault_hetzner_dns_rfc1918_zones | default([]) }}"
  - name: vernetzen
    zones: "{{ vault_hetzner_dns_vernetzen_zones | default([]) }}"
  - name: yukon
    zones: "{{ vault_hetzner_dns_yukon_zones | default([]) }}"

dns_hetzner_cloud_managed_rrsets:
  - token_group: rfc1918
    zone: rfc1918.host
    name: msg-sun99-ntfysys-099096
    fqdn: msg-sun99-ntfysys-099096.rfc1918.host
    type: A
    ttl: 300
    values:
      - 172.16.99.96
    comment: codex ntfy service vip
  - token_group: rfc1918
    zone: rfc1918.host
    name: msg-sun99-ntfysys
    fqdn: msg-sun99-ntfysys.rfc1918.host
    type: CNAME
    ttl: 300
    values:
      - msg-sun99-ntfysys-099096.rfc1918.host.
    comment: codex ntfy service cname
