---
all:
  children:
    install_targets:
      hosts:
        target_system_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
        target_system_remote:
          ansible_host: 10.9.8.7
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          netboot_enabled: true
          netboot_interface_name: eth0
          netboot_mac_address: "52:54:00:12:34:56"
          netboot_type: dhcp
          netboot_dhcp_client_options:
            - "class-id=PXEClient:Arch:00000:UNDI:002001"
          netboot_os_type: linux
          netboot_os_name: gentoo
          netboot_os_version: stage4-current
          netboot_machine_type: qemu
          netboot_platform: uefi
          netboot_arch: amd64
          netboot_role: installer
    netboot_publishers:
      hosts:
        netboot_control_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    qemu_hypervisors:
      hosts:
        qemu_control_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    ci_controllers:
      hosts:
        vm_jenkins_controller:
          ansible_host: 10.66.40.10
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    binpkg_repositories:
      hosts:
        vm_binpkg_repository:
          ansible_host: 10.66.40.20
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    nexus_repositories:
      hosts:
        vm_nexus_repository:
          ansible_host: 10.66.40.30
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    container_service_hosts:
      hosts:
        vm_container_services:
          ansible_host: 10.66.20.10
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    workstation_hosts:
      hosts:
        vm_workstation_nscde:
          ansible_host: 10.66.20.40
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    observability_prometheus:
      hosts:
        vm_observability_prometheus:
          ansible_host: 10.66.30.40
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    observability_grafana:
      hosts:
        vm_observability_grafana:
          ansible_host: 10.66.30.41
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    identity_controllers:
      hosts:
        vm_identity_controller:
          ansible_host: 10.66.30.10
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    elasticsearch_nodes:
      hosts:
        vm_elasticsearch_node01:
          ansible_host: 10.66.30.21
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        vm_elasticsearch_node02:
          ansible_host: 10.66.30.22
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        vm_elasticsearch_node03:
          ansible_host: 10.66.30.23
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    elasticsearch_test_nodes:
      hosts:
        vm_elasticsearch_test:
          ansible_host: 10.9.8.91
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    kibana_interfaces:
      hosts:
        vm_kibana_interface:
          ansible_host: 10.66.30.30
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    builder_farm_nodes:
      hosts:
        builder_farm_node01:
          ansible_host: 10.66.40.11
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        builder_farm_node02:
          ansible_host: 10.66.40.12
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        builder_farm_node03:
          ansible_host: 10.66.40.13
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        builder_farm_node04:
          ansible_host: 10.66.40.14
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        builder_farm_node05:
          ansible_host: 10.66.40.15
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
        builder_farm_node06:
          ansible_host: 10.66.40.16
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    aaa_domain_clients:
      hosts:
        vm_jenkins_controller:
        vm_binpkg_repository:
        vm_elasticsearch_node01:
        vm_elasticsearch_node02:
        vm_elasticsearch_node03:
        vm_kibana_interface:
        builder_farm_node01:
        builder_farm_node02:
        builder_farm_node03:
        builder_farm_node04:
        builder_farm_node05:
        builder_farm_node06:
    routeros_pathb:
      hosts:
        routeros_pathb_primary:
          ansible_host: 10.9.8.1
          ansible_user: admin
    routeros_rfc99_gateways:
      hosts:
        gw_rfc99_mkccr2004_16g_example:
          ansible_connection: local
          ansible_user: admin
