---
all:
  children:
    install_targets:
      hosts:
        target_system_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
        target_system_remote:
          ansible_host: 10.9.8.7
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    ntfy_servers:
      hosts:
        ntfy_primary:
          ansible_host: 10.64.64.200
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
