---
all:
  children:
    install_targets:
      hosts:
        target_system_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
        target_system_remote:
          ansible_host: 10.9.8.7
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
          netboot_enabled: true
          netboot_interface_name: eth0
          netboot_mac_address: "52:54:00:12:34:56"
          netboot_type: dhcp
          netboot_dhcp_client_options:
            - "class-id=PXEClient:Arch:00000:UNDI:002001"
          netboot_os_type: linux
          netboot_os_name: gentoo
          netboot_os_version: stage4-current
          netboot_machine_type: qemu
          netboot_platform: uefi
          netboot_arch: amd64
          netboot_role: installer
    netboot_publishers:
      hosts:
        netboot_control_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
