---
routeros_rfc99_gateway_apply: false
routeros_rfc99_gateway_identity: gw-rfc99-mkccr2004-16g
routeros_rfc99_gateway_wan_interface: sfp-sfpplus1
routeros_rfc99_gateway_lan_uplink_interface: sfp-sfpplus2
routeros_rfc99_gateway_wan_mode: dhcp
routeros_rfc99_gateway_dns_servers:
  - 9.9.9.9
  - 8.8.8.8
routeros_rfc99_gateway_syslog_remote_host: 172.16.99.80
