---
all:
  children:
    install_targets:
      hosts:
        vm_container_services:
          ansible_host: 10.9.8.89
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
