---
distcc_farm_default_enabled: false
distcc_farm_default_client_enabled: false
distcc_farm_default_worker_enabled: false
distcc_farm_default_port: 3632
distcc_farm_default_jobs: 8
distcc_farm_default_nice: 5
distcc_farm_default_listen_address: 0.0.0.0
distcc_farm_default_allowed_client_cidrs: []
distcc_farm_default_makeopts_jobs: ""
distcc_farm_default_makeopts_load: ""
distcc_farm_default_hosts: []
distcc_farm_default_service_user: distcc
distcc_farm_default_service_group: distcc
distcc_farm_default_runlevel: default
distcc_farm_default_compression: true
distcc_farm_default_cpp_mode: false
distcc_farm_default_builder_fabric_name: builder-fabric
distcc_farm_default_builder_fabric_cidr: ""
distcc_farm_default_worker_metadata: {}
