#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

mapfile -t shell_scripts < <(find \
  "${REPO_ROOT}/scripts" \
  "${REPO_ROOT}/gentoo-virt-qemu" \
  "${REPO_ROOT}/scripts" \
  "${REPO_ROOT}/gentoo_stage4_llvm_split-usr_no-multilib_hardened/gentoo-liveiso-ansible/scripts" \
  "${REPO_ROOT}/tests/shell" \
  -type f -name '*.sh' | sort)

for script in "${shell_scripts[@]}"; do
  bash -n "${script}"
done

bash "${SCRIPT_DIR}/test_generate_ansible_python_setup.sh"
bash "${SCRIPT_DIR}/test_ansible_vault_tools.sh"
bash "${SCRIPT_DIR}/test_hetzner_dns_vault.sh"
bash "${SCRIPT_DIR}/test_hetzner_dns_plan_from_netbox.sh"
bash "${SCRIPT_DIR}/test_hetzner_dns_inventory_report.sh"
bash "${SCRIPT_DIR}/test_hetzner_dns_apply_and_hosts_fallback.sh"
bash "${SCRIPT_DIR}/test_local_network_inventory.sh"
bash "${SCRIPT_DIR}/test_ntfy_tools.sh"
bash "${SCRIPT_DIR}/test_ntfy_server_role.sh"
bash "${SCRIPT_DIR}/test_github_project_management.sh"
bash "${SCRIPT_DIR}/test_control_flow_tools.sh"
bash "${SCRIPT_DIR}/test_installer_override_paths.sh"
bash "${SCRIPT_DIR}/test_portage_profile_lint.sh"
bash "${SCRIPT_DIR}/test_ansible_lint.sh"
bash "${SCRIPT_DIR}/test_system_profiles.sh"
bash "${SCRIPT_DIR}/test_role_package_taxonomy.sh"
bash "${SCRIPT_DIR}/test_container_service_roles.sh"
bash "${SCRIPT_DIR}/test_container_service_image_definitions.sh"
bash "${SCRIPT_DIR}/test_mcp_control_plane_services.sh"
bash "${SCRIPT_DIR}/test_ci_builder_farm_roles.sh"
bash "${SCRIPT_DIR}/test_identity_aaa_roles.sh"
bash "${SCRIPT_DIR}/test_identity_source_of_truth.sh"
bash "${SCRIPT_DIR}/test_identity_apply_plan.sh"
bash "${SCRIPT_DIR}/test_live_ipa_client_enrollment.sh"
bash "${SCRIPT_DIR}/test_nfs_storage_client_profile.sh"
bash "${SCRIPT_DIR}/test_netbox_essential_integrations.sh"
bash "${SCRIPT_DIR}/test_netbox_inventory_intake.sh"
bash "${SCRIPT_DIR}/test_profile_version_pinning.sh"
bash "${SCRIPT_DIR}/test_export_netbox_provisioning_inventory.sh"
bash "${SCRIPT_DIR}/test_proxmox_create_stage4_service_vm.sh"
bash "${SCRIPT_DIR}/test_proxmox_create_workstation_nscde_gpu_vm.sh"
bash "${SCRIPT_DIR}/test_workstation_session_stack.sh"
bash "${SCRIPT_DIR}/test_workstation_package_policy.sh"
bash "${SCRIPT_DIR}/test_capture_gentoo_emerge_state.sh"
bash "${SCRIPT_DIR}/test_network_planning_docs.sh"
bash "${SCRIPT_DIR}/test_bignetwork_smoketest_roles.sh"
bash "${SCRIPT_DIR}/test_bignetwork_vault.sh"
bash "${SCRIPT_DIR}/test_private_ca_vault.sh"
bash "${SCRIPT_DIR}/test_operational_validation_playbooks.sh"
bash "${SCRIPT_DIR}/test_observability_access_roles.sh"
bash "${SCRIPT_DIR}/test_vm_redfish_emulator_role.sh"
bash "${SCRIPT_DIR}/test_service_validator.sh"
bash "${SCRIPT_DIR}/test_slo_service_validator.sh"
bash "${SCRIPT_DIR}/test_migrate_container_services_runtime.sh"
bash "${SCRIPT_DIR}/test_telemetry_observability_roles.sh"
bash "${SCRIPT_DIR}/test_binpkg_repository_roles.sh"
bash "${SCRIPT_DIR}/test_nexus_repository_roles.sh"
bash "${SCRIPT_DIR}/test_hasslehoff_backup_tools.sh"
bash "${SCRIPT_DIR}/test_netboot_assets.sh"
bash "${SCRIPT_DIR}/test_routeros_pathb_role.sh"
bash "${SCRIPT_DIR}/test_routeros_rfc99_gateway_role.sh"
bash "${SCRIPT_DIR}/test_routeros_serial_command.sh"
bash "${SCRIPT_DIR}/test_install_codex_approval_watcher_service.sh"
bash "${SCRIPT_DIR}/test_install_codex_ntfy_reply_listener_service.sh"
bash "${SCRIPT_DIR}/test_workflow_manifests.sh"
bash "${SCRIPT_DIR}/test_zfs_layout_specs.sh"
bash "${SCRIPT_DIR}/test_build_stage3_qcow.sh"
bash "${SCRIPT_DIR}/test_validate_llvm_qcow_builder.sh"
bash "${SCRIPT_DIR}/test_generate_cloud_init_seed.sh"
bash "${SCRIPT_DIR}/test_ntfy_tools.sh"
bash "${SCRIPT_DIR}/test_watch_vm_serial.sh"
bash "${SCRIPT_DIR}/test_publish_wiki.sh"
bash "${SCRIPT_DIR}/test_publish_container_ghcr.sh"
bash "${SCRIPT_DIR}/test_build_gentoo_rootfs_container.sh"
bash "${SCRIPT_DIR}/test_run_container_service_layer_build_pathb.sh"
bash "${SCRIPT_DIR}/test_sync_binpkgs_to_repo.sh"
bash "${SCRIPT_DIR}/test_watch_sync_binpkgs_to_repo.sh"
bash "${SCRIPT_DIR}/test_export_build_metrics.sh"
bash "${SCRIPT_DIR}/test_qemu_memory_drives.sh"
bash "${SCRIPT_DIR}/test_qemu_launch_pathb_vm.sh"
bash "${SCRIPT_DIR}/test_qemu_launch_binpkg_repository_vm.sh"
bash "${SCRIPT_DIR}/test_qemu_launch_container_services_vm.sh"
bash "${SCRIPT_DIR}/test_qemu_launch_elasticsearch_test_vm.sh"
bash "${SCRIPT_DIR}/test_qemu_launch_cloudinit_vm.sh"
bash "${SCRIPT_DIR}/test_qemu_launch_stage3_vm.sh"
bash "${SCRIPT_DIR}/test_qemu_launch_minimal_vm.sh"
bash "${SCRIPT_DIR}/test_qemu_pci_remap.sh"

printf 'PASS: %s\n' "$(basename "$0")"
