#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ANSIBLE_ROOT="${REPO_ROOT}/gentoo_stage4_llvm_split-usr_no-multilib_hardened/gentoo-liveiso-ansible"
RENDER_ROOT="$(mktemp -d)"

cleanup() {
  rm -rf "${RENDER_ROOT}"
}
trap cleanup EXIT

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

assert_file_contains() {
  local path="$1"
  local needle="$2"
  grep -Fq "${needle}" "${path}" || fail "expected '${needle}' in ${path}"
}

assert_file_not_contains() {
  local path="$1"
  local needle="$2"
  if grep -Fq "${needle}" "${path}"; then
    fail "did not expect '${needle}' in ${path}"
  fi
}

test_routeros_rfc99_gateway_assets_exist() {
  assert_file_contains "${ANSIBLE_ROOT}/playbooks/routeros-rfc99-gateway.yml" "hosts: routeros_rfc99_gateways"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_expected_model: CCR2004-16G-2S+PC"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_wan_interface: sfp-sfpplus1"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_lan_uplink_interface: sfp-sfpplus2"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_dns_static_records"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_dhcp_next_server: \"\""
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_dhcp_options: []"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_dhcp_static_leases: []"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_target_version: 7.22.3"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_service_vips: []"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_static_routes: []"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_dst_nat_rules: []"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_src_nat_rules: []"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "routeros_rfc99_gateway_service_vips:"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "172.16.99.92/32"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "172.16.99.93/32"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "routeros_rfc99_gateway_dst_nat_rules:"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "routeros_rfc99_gateway_src_nat_rules:"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "lab-sun99-x1gen8-099082.rfc1918.dev"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "x1gen8-pxe-bootfile"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "54:05:DB:34:CC:75"
  assert_file_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "172.16.99.82"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/templates/routeros-rfc99-gateway.rsc.j2" "Generated by Ansible role: routeros_rfc99_gateway"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/templates/routeros-rfc99-gateway-manifest.json.j2" "\"kind\": \"RouterOSRFC99GatewayManifest\""
  assert_file_contains "${REPO_ROOT}/docs/ROUTEROS-RFC99-GATEWAY.md" "# RouterOS RFC99 Gateway Role"
  assert_file_contains "${REPO_ROOT}/docs/wiki/RouterOS-RFC99-Gateway.md" "# RouterOS RFC99 Gateway Role"
  assert_file_contains "${REPO_ROOT}/docs/workflows/stage4-routeros-rfc99-gateway-deployment.json" "\"name\": \"stage4-routeros-rfc99-gateway-deployment\""
}

test_routeros_rfc99_gateway_playbook_syntax() {
  (
    cd "${ANSIBLE_ROOT}"
    ANSIBLE_STDOUT_CALLBACK=default ANSIBLE_CALLBACKS_ENABLED=control_flow \
      ansible-playbook -i inventories/examples/hosts.yml playbooks/routeros-rfc99-gateway.yml --syntax-check > /dev/null
  )
}

test_routeros_rfc99_gateway_rendered_config() {
  (
    cd "${ANSIBLE_ROOT}"
    ANSIBLE_STDOUT_CALLBACK=default ANSIBLE_CALLBACKS_ENABLED=control_flow \
      ansible-playbook -i inventories/examples/hosts.yml playbooks/routeros-rfc99-gateway.yml \
      -e "routeros_rfc99_gateway_render_root=${RENDER_ROOT}" > /dev/null
  )

  local rsc="${RENDER_ROOT}/gw_rfc99_mkccr2004_16g_example-rfc99-gateway.rsc"
  local manifest="${RENDER_ROOT}/gw_rfc99_mkccr2004_16g_example-rfc99-gateway.json"

  [[ -s "${rsc}" ]] || fail "expected rendered RouterOS RSC at ${rsc}"
  [[ -s "${manifest}" ]] || fail "expected rendered RouterOS manifest at ${manifest}"

  assert_file_contains "${rsc}" ':local cfgTag "RFC99-CCR2004-16G.001"'
  assert_file_contains "${rsc}" '/system identity set name="gw-rfc99-mkccr2004-16g"'
  assert_file_contains "${rsc}" 'set [find default-name="ether1"] name="ge1"'
  assert_file_contains "${rsc}" 'set [find default-name="ether16"] name="ge16"'
  assert_file_contains "${rsc}" '/interface ethernet set [find default-name="sfp-sfpplus1"] comment="WAN uplink"'
  assert_file_contains "${rsc}" '/interface ethernet set [find default-name="sfp-sfpplus2"] comment="LAN switch uplink"'
  assert_file_contains "${rsc}" '/interface list member add list=WAN interface=sfp-sfpplus1'
  assert_file_contains "${rsc}" '/interface bridge add name=br-lan protocol-mode=rstp vlan-filtering=yes'
  assert_file_contains "${rsc}" '/interface bridge port add bridge=br-lan interface=sfp-sfpplus2'
  assert_file_contains "${rsc}" '/interface vlan add name=vlan1098-pathb-lab-services vlan-id=1098 interface=br-lan'
  assert_file_contains "${rsc}" '/ip address add address=10.9.8.1/24 interface=vlan1098-pathb-lab-services comment="RFC99 VLAN pathb-lab-services"'
  assert_file_contains "${rsc}" '/ip address add address=172.16.99.92/32 interface=br-lan comment="RFC99 service VIP obs-sun99-esvip-099092"'
  assert_file_contains "${rsc}" '/ip address add address=172.16.99.93/32 interface=br-lan comment="RFC99 service VIP log-sun99-rsyslog-099093"'
  assert_file_contains "${rsc}" '/ip address remove [find where interface="sfp-sfpplus1" and dynamic=no]'
  assert_file_contains "${rsc}" '/ip route remove [find where dst-address="0.0.0.0/0" and dynamic=no and gateway="192.168.1.254"]'
  if grep -q 'X12AGAIN transit' "${rsc}"; then
    fail "rendered RouterOS config still contains obsolete X12AGAIN transit routes"
  fi
  assert_file_contains "${rsc}" '/ip dns static add name="msg-sun99-ntfysys-099096.rfc1918.host" type=A address=172.16.99.96 ttl=5m comment="codex ntfy service vip"'
  assert_file_contains "${rsc}" '/ip dns static add name="msg-sun99-ntfysys.rfc1918.host" type=CNAME cname="msg-sun99-ntfysys-099096.rfc1918.host" ttl=5m comment="codex ntfy service cname"'
  assert_file_contains "${rsc}" '/ip dns static add name="obs-sun99-esvip-099092.rfc1918.host" type=A address=172.16.99.92 ttl=5m comment="codex elasticsearch sun99 vip"'
  assert_file_contains "${rsc}" '/ip dns static add name="obs-sun99-esvip.rfc1918.host" type=CNAME cname="obs-sun99-esvip-099092.rfc1918.host" ttl=5m comment="codex elasticsearch sun99 cname"'
  assert_file_contains "${rsc}" '/ip dns static add name="log-sun99-rsyslog-099093.rfc1918.host" type=A address=172.16.99.93 ttl=5m comment="codex rsyslog service vip"'
  assert_file_contains "${rsc}" '/ip dns static add name="log-sun99-rsyslog.rfc1918.host" type=CNAME cname="log-sun99-rsyslog-099093.rfc1918.host" ttl=5m comment="codex rsyslog service cname"'
  assert_file_contains "${rsc}" '/ip dns static add name="gw-rfc99-mkccr2004-16g.rfc1918.host" type=A address=172.16.99.1 ttl=5m comment="codex RouterOS CCR2004 gateway API"'
  assert_file_contains "${rsc}" '/ip dns static add name="agx-rfc99-bunnydev.rfc1918.host" type=A address=172.16.99.34 ttl=5m comment="thor agx rj45 management"'
  assert_file_contains "${rsc}" '/ip dns static add name="boot-sun99-netboot-099088.rfc1918.host" type=A address=172.16.99.88 ttl=5m comment="codex netboot publisher vm"'
  assert_file_contains "${rsc}" '/ip dns static add name="boot-sun99-netboot.rfc1918.host" type=CNAME cname="boot-sun99-netboot-099088.rfc1918.host" ttl=5m comment="codex netboot publisher cname"'
  assert_file_contains "${rsc}" '/ip dns static add name="lab-sun99-x1gen8-099082.rfc1918.dev" type=A address=172.16.99.82 ttl=5m comment="codex ThinkPad X1 Gen8 workstation netboot"'
  assert_file_contains "${rsc}" '/ip dns static add name="lab-sun99-x1gen8.rfc1918.dev" type=CNAME cname="lab-sun99-x1gen8-099082.rfc1918.dev" ttl=5m comment="codex ThinkPad X1 Gen8 workstation cname"'
  assert_file_contains "${rsc}" '/ip settings set send-redirects=no accept-redirects=no secure-redirects=no'
  assert_file_contains "${rsc}" '/ip pool add name="rfc99-management-compat-dhcp" ranges=172.16.99.150-172.16.99.158'
  assert_file_contains "${rsc}" '/ip dhcp-server network add address=172.16.99.0/24 gateway=172.16.99.1 netmask=24 dns-server=172.16.99.1 next-server=172.16.99.88 comment="RFC99 management compatibility DHCP"'
  assert_file_contains "${rsc}" '/ip dhcp-server add name="rfc99-management-compat" interface=br-lan address-pool=rfc99-management-compat-dhcp lease-time=1h disabled=no'
  assert_file_contains "${rsc}" "/ip dhcp-server option add name=\"k10-pxe-bootfile\" code=67 value=\"'k10-ipxe.efi'\""
  assert_file_contains "${rsc}" "/ip dhcp-server option add name=\"x1gen8-pxe-bootfile\" code=67 value=\"'x1gen8-ipxe.efi'\""
  assert_file_contains "${rsc}" '/ip dhcp-server lease set [find where mac-address="84:47:09:5F:21:64"] address=172.16.99.156 server=rfc99-management-compat comment="gmktek-k10-stage5-ipxe" dhcp-option=k10-pxe-bootfile'
  assert_file_contains "${rsc}" '/ip dhcp-server lease set [find where mac-address="54:05:DB:34:CC:75"] address=172.16.99.82 server=rfc99-management-compat comment="lab-sun99-x1gen8-099082-ipxe" dhcp-option=x1gen8-pxe-bootfile'
  assert_file_contains "${rsc}" '/ip service set ssh disabled=no port=22 address=172.16.99.0/24,10.9.8.0/24,10.128.128.0/24'
  assert_file_contains "${rsc}" '/certificate add name="rfc99-gw-selfsigned-template" common-name="gw-rfc99-mkccr2004-16g.rfc1918.host"'
  assert_file_contains "${rsc}" '/certificate sign "rfc99-gw-selfsigned-template" name="rfc99-gw-selfsigned"'
  assert_file_contains "${rsc}" '/ip service set www-ssl disabled=no port=443 address=172.16.99.0/24,10.9.8.0/24,10.128.128.0/24 certificate=rfc99-gw-selfsigned tls-version=only-1.2'
  assert_file_contains "${rsc}" '/ip service set api-ssl disabled=no port=8729 address=172.16.99.0/24,10.9.8.0/24,10.128.128.0/24 certificate=rfc99-gw-selfsigned tls-version=only-1.2'
  assert_file_contains "${rsc}" '/system logging action set remote remote=172.16.99.80 remote-port=514 remote-protocol=udp syslog-time-format=bsd-syslog'
  assert_file_contains "${rsc}" '/system logging add action=remote topics=info'
  assert_file_contains "${rsc}" '/ip service set telnet disabled=yes'
  assert_file_contains "${rsc}" '/ip service set ftp disabled=yes'
  assert_file_contains "${rsc}" '/ip service set www disabled=yes'
  assert_file_contains "${rsc}" '/ip service set api disabled=yes'
  assert_file_contains "${rsc}" ':if ([:len [/ip service find where name="reverse-proxy"]] > 0) do={ /ip service set reverse-proxy disabled=yes }'
  assert_file_contains "${rsc}" '/tool bandwidth-server set enabled=no'
  assert_file_contains "${rsc}" '/snmp set enabled=no contact="RFC99" location="CCR2004-16G-2S+PC"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=dstnat action=dst-nat protocol=tcp dst-address=172.16.99.92 dst-port=9200 to-addresses=172.16.99.89 to-ports=9200 comment="RFC99 service dstnat obs-sun99-esvip-099092 elasticsearch to container-services HAProxy"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=dstnat action=dst-nat protocol=tcp dst-address=172.16.99.92 dst-port=443 to-addresses=172.16.99.89 to-ports=443 comment="RFC99 service dstnat obs-sun99-esvip-099092 https to container-services HAProxy"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=dstnat action=dst-nat protocol=tcp dst-address=172.16.99.93 dst-port=6514 to-addresses=172.16.99.89 to-ports=6514 comment="RFC99 service dstnat log-sun99-rsyslog-099093 rsyslog to container-services HAProxy"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=srcnat action=masquerade protocol=tcp src-address=172.16.99.0/24 dst-address=172.16.99.89 dst-port=9200 comment="RFC99 service srcnat obs-sun99-esvip-099092 hairpin to container-services HAProxy"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=srcnat action=masquerade protocol=tcp src-address=172.16.99.0/24 dst-address=172.16.99.89 comment="RFC99 service srcnat obs-sun99-esvip-099092 web hairpin to container-services HAProxy"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=srcnat action=masquerade protocol=tcp src-address=172.16.99.0/24 dst-address=172.16.99.89 dst-port=6514 comment="RFC99 service srcnat log-sun99-rsyslog-099093 hairpin to container-services HAProxy"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=srcnat action=masquerade out-interface-list=WAN comment="RFC99 WAN SNAT"'
  assert_file_contains "${rsc}" '/ip firewall filter add chain=output action=drop protocol=icmp icmp-options=5:0-255 out-interface-list=LAN comment="RFC99 output suppress LAN ICMP redirects"'
  assert_file_not_contains "${rsc}" '172.16.229.1/22'
  assert_file_not_contains "${rsc}" '172.16.230.1/22'

  assert_file_contains "${manifest}" '"wanInterface": "sfp-sfpplus1"'
  assert_file_contains "${manifest}" '"targetVersion": "7.22.3"'
  assert_file_contains "${manifest}" '"lanUplinkInterface": "sfp-sfpplus2"'
  assert_file_contains "${manifest}" '"apiSslEnabled": true'
  assert_file_contains "${manifest}" '"ether16": "ge16"'
  assert_file_contains "${manifest}" '"serviceVips":'
  assert_file_contains "${manifest}" '"staticRoutes":'
  assert_file_contains "${manifest}" '"dstNatRules":'
  assert_file_contains "${manifest}" '"srcNatRules":'
}

test_routeros_rfc99_gateway_assets_exist
test_routeros_rfc99_gateway_playbook_syntax
test_routeros_rfc99_gateway_rendered_config

printf 'PASS: %s\n' "$(basename "$0")"
