#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ANSIBLE_ROOT="${REPO_ROOT}/gentoo_stage4_llvm_split-usr_no-multilib_hardened/gentoo-liveiso-ansible"
RENDER_ROOT="$(mktemp -d)"

cleanup() {
  rm -rf "${RENDER_ROOT}"
}
trap cleanup EXIT

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

assert_file_contains() {
  local path="$1"
  local needle="$2"
  grep -Fq "${needle}" "${path}" || fail "expected '${needle}' in ${path}"
}

assert_file_not_contains() {
  local path="$1"
  local needle="$2"
  if grep -Fq "${needle}" "${path}"; then
    fail "did not expect '${needle}' in ${path}"
  fi
}

test_routeros_rfc99_gateway_assets_exist() {
  assert_file_contains "${ANSIBLE_ROOT}/playbooks/routeros-rfc99-gateway.yml" "hosts: routeros_rfc99_gateways"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_expected_model: CCR2004-16G-2S+PC"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_wan_interface: sfp-sfpplus1"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/defaults/main.yml" "routeros_rfc99_gateway_lan_uplink_interface: sfp-sfpplus2"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/templates/routeros-rfc99-gateway.rsc.j2" "Generated by Ansible role: routeros_rfc99_gateway"
  assert_file_contains "${ANSIBLE_ROOT}/roles/routeros_rfc99_gateway/templates/routeros-rfc99-gateway-manifest.json.j2" "\"kind\": \"RouterOSRFC99GatewayManifest\""
  assert_file_contains "${REPO_ROOT}/docs/ROUTEROS-RFC99-GATEWAY.md" "# RouterOS RFC99 Gateway Role"
  assert_file_contains "${REPO_ROOT}/docs/wiki/RouterOS-RFC99-Gateway.md" "# RouterOS RFC99 Gateway Role"
  assert_file_contains "${REPO_ROOT}/docs/workflows/stage4-routeros-rfc99-gateway-deployment.json" "\"name\": \"stage4-routeros-rfc99-gateway-deployment\""
}

test_routeros_rfc99_gateway_playbook_syntax() {
  (
    cd "${ANSIBLE_ROOT}"
    ANSIBLE_STDOUT_CALLBACK=default ANSIBLE_CALLBACKS_ENABLED=control_flow \
      ansible-playbook -i inventories/examples/hosts.yml playbooks/routeros-rfc99-gateway.yml --syntax-check >/dev/null
  )
}

test_routeros_rfc99_gateway_rendered_config() {
  (
    cd "${ANSIBLE_ROOT}"
    ANSIBLE_STDOUT_CALLBACK=default ANSIBLE_CALLBACKS_ENABLED=control_flow \
      ansible-playbook -i inventories/examples/hosts.yml playbooks/routeros-rfc99-gateway.yml \
        -e "routeros_rfc99_gateway_render_root=${RENDER_ROOT}" >/dev/null
  )

  local rsc="${RENDER_ROOT}/gw_rfc99_mkccr2004_16g_example-rfc99-gateway.rsc"
  local manifest="${RENDER_ROOT}/gw_rfc99_mkccr2004_16g_example-rfc99-gateway.json"

  [[ -s "${rsc}" ]] || fail "expected rendered RouterOS RSC at ${rsc}"
  [[ -s "${manifest}" ]] || fail "expected rendered RouterOS manifest at ${manifest}"

  assert_file_contains "${rsc}" ':local cfgTag "RFC99-CCR2004-16G.001"'
  assert_file_contains "${rsc}" '/system identity set name="gw-rfc99-mkccr2004-16g"'
  assert_file_contains "${rsc}" 'set [find default-name="ether1"] name="ge1"'
  assert_file_contains "${rsc}" 'set [find default-name="ether16"] name="ge16"'
  assert_file_contains "${rsc}" '/interface ethernet set [find default-name="sfp-sfpplus1"] comment="WAN uplink"'
  assert_file_contains "${rsc}" '/interface ethernet set [find default-name="sfp-sfpplus2"] comment="LAN switch uplink"'
  assert_file_contains "${rsc}" '/interface list member add list=WAN interface=sfp-sfpplus1'
  assert_file_contains "${rsc}" '/interface bridge add name=br-lan protocol-mode=rstp vlan-filtering=yes'
  assert_file_contains "${rsc}" '/interface bridge port add bridge=br-lan interface=sfp-sfpplus2'
  assert_file_contains "${rsc}" '/interface vlan add name=vlan1098-pathb-lab-services vlan-id=1098 interface=br-lan'
  assert_file_contains "${rsc}" '/ip address add address=10.9.8.1/24 interface=vlan1098-pathb-lab-services comment="RFC99 VLAN pathb-lab-services"'
  assert_file_contains "${rsc}" '/ip address remove [find where interface="sfp-sfpplus1" and dynamic=no]'
  assert_file_contains "${rsc}" '/ip route remove [find where dst-address="0.0.0.0/0" and dynamic=no and gateway="192.168.1.254"]'
  assert_file_contains "${rsc}" '/ip dhcp-server disable [find]'
  assert_file_contains "${rsc}" '/ip service set ssh disabled=no port=22 address=172.16.99.0/24,10.9.8.0/24,10.128.128.0/24'
  assert_file_contains "${rsc}" '/certificate add name="rfc99-gw-selfsigned-template" common-name="gw-rfc99-mkccr2004-16g.rfc1918.host"'
  assert_file_contains "${rsc}" '/certificate sign "rfc99-gw-selfsigned-template" name="rfc99-gw-selfsigned"'
  assert_file_contains "${rsc}" '/ip service set www-ssl disabled=no port=443 address=172.16.99.0/24,10.9.8.0/24,10.128.128.0/24 certificate=rfc99-gw-selfsigned tls-version=only-1.2'
  assert_file_contains "${rsc}" '/ip service set api-ssl disabled=no port=8729 address=172.16.99.0/24,10.9.8.0/24,10.128.128.0/24 certificate=rfc99-gw-selfsigned tls-version=only-1.2'
  assert_file_contains "${rsc}" '/system logging action set remote remote=172.16.99.80 remote-port=514 remote-protocol=udp syslog-time-format=bsd-syslog'
  assert_file_contains "${rsc}" '/system logging add action=remote topics=info'
  assert_file_contains "${rsc}" '/ip service set telnet disabled=yes'
  assert_file_contains "${rsc}" '/ip service set ftp disabled=yes'
  assert_file_contains "${rsc}" '/ip service set www disabled=yes'
  assert_file_contains "${rsc}" '/ip service set api disabled=yes'
  assert_file_contains "${rsc}" ':if ([:len [/ip service find where name="reverse-proxy"]] > 0) do={ /ip service set reverse-proxy disabled=yes }'
  assert_file_contains "${rsc}" '/tool bandwidth-server set enabled=no'
  assert_file_contains "${rsc}" '/snmp set enabled=no contact="RFC99" location="CCR2004-16G-2S+PC"'
  assert_file_contains "${rsc}" '/ip firewall nat add chain=srcnat action=masquerade out-interface-list=WAN comment="RFC99 WAN SNAT"'
  assert_file_not_contains "${rsc}" '172.16.229.1/22'
  assert_file_not_contains "${rsc}" '172.16.230.1/22'

  assert_file_contains "${manifest}" '"wanInterface": "sfp-sfpplus1"'
  assert_file_contains "${manifest}" '"lanUplinkInterface": "sfp-sfpplus2"'
  assert_file_contains "${manifest}" '"apiSslEnabled": true'
  assert_file_contains "${manifest}" '"ether16": "ge16"'
}

test_routeros_rfc99_gateway_assets_exist
test_routeros_rfc99_gateway_playbook_syntax
test_routeros_rfc99_gateway_rendered_config

printf 'PASS: %s\n' "$(basename "$0")"
