#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ANSIBLE_ROOT="gentoo_stage4_llvm_split-usr_no-multilib_hardened/gentoo-liveiso-ansible"

assert_file() {
  local path="$1"
  if [[ ! -f "${ROOT_DIR}/${path}" ]]; then
    echo "missing file: ${path}" >&2
    exit 1
  fi
}

assert_contains() {
  local path="$1"
  local needle="$2"
  if ! grep -Fq "${needle}" "${ROOT_DIR}/${path}"; then
    echo "missing '${needle}' in ${path}" >&2
    exit 1
  fi
}

assert_file "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml"
assert_file "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.metadata.yml"
assert_file "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-intel-platform.packages"
assert_file "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages"
assert_file "${ANSIBLE_ROOT}/profile-service-atoms/stage5-role-service-atoms.yml"
assert_file "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml"
assert_file "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml"
assert_file "${ANSIBLE_ROOT}/inventories/local-network/group_vars/all/dns_hetzner_cloud.yml"
assert_file "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml"
assert_file "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml"
assert_file "${ANSIBLE_ROOT}/playbooks/ipa-client-live-apply.yml"
assert_file "docs/M70-FORGE-AUTOMATION-ADMIN.md"
assert_file "docs/wiki/M70-Forge-Automation-Admin.md"
assert_file "docs/runbooks/m70-automation-admin-install.md"
assert_file "docs/X11SCL-IF-FORGE-AUTOMATION-ADMIN.md"
assert_file "docs/wiki/X11SCL-IF-Forge-Automation-Admin.md"
assert_file "docs/runbooks/x11scl-if-forge-admin-build.md"

assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "profile_id: metal-forge-automation-admin"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "stage5_profile: metal-forge-automation-admin"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "stage5-metal-intel-platform.packages"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" 'ACCEPT_LICENSE="*.*"'
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "automation_admin:"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "x12again_sol_wrapper_path: /root/.ssh/codex.d/ipmi.d/ipmi-prinzessin"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "forge_memory_spool_path: /var/lib/forge-memory/spool"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.metadata.yml" "id: metal-forge-automation-admin"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-intel-platform.packages" "sys-firmware/intel-microcode"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-intel-platform.packages" "sys-kernel/linux-firmware"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "qat_c3xxx"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "coretemp"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "it87"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "lm_sensors"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.metadata.yml" "kernel-ready-consumer-validation-required"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.metadata.yml" "host_sensor_modules"

assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "app-admin/ansible"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" ">=app-editors/emacs-30"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "app-shells/bash-completion"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "app-text/tree"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "sys-apps/eza"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "sys-fs/xfsprogs"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "sys-fs/xfsdump"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "dev-vcs/git"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "dev-vcs/git-lfs"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "dev-vcs/tig"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "net-analyzer/nmap"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "net-analyzer/tcpdump"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "sys-apps/ipmitool"
assert_contains "${ANSIBLE_ROOT}/profile-package-lists/stage5-metal-forge-automation-admin.packages" "sys-fs/zfs"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "external_tooling:"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "command: gh"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "portage_config_files:"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" "00-eixrc"
assert_contains "${ANSIBLE_ROOT}/profile-definitions/metal-forge-automation-admin.yml" 'OVERLAY_CACHE_METHOD="assign"'
assert_contains "${ANSIBLE_ROOT}/roles/preflight/tasks/load_profile_definition.yml" "resolved_portage_config_files"
assert_contains "${ANSIBLE_ROOT}/roles/portage/tasks/main.yml" "Assert extra Portage config file paths stay under allowed config roots"
assert_contains "${ANSIBLE_ROOT}/roles/portage/tasks/main.yml" "portage_config_file.key.startswith('/etc/eixrc/')"
assert_contains "${ANSIBLE_ROOT}/roles/portage/tasks/main.yml" "Write extra Portage config files from selected profile definitions"

assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "automation_admin_hosts:"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "admin_sun99_forge_099070:"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "ansible_host: 172.16.99.70"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "fqdn: admin-sun99-forge-099070.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "stage5_profile: metal-forge-automation-admin"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "primary_nic_mac: \"00:07:32:78:65:C6\""
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "connected_switch_port: ge14"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "pdu_outlet: \"4\""
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "pdu_outlet_label: admin-sun99-forge"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "observed_memory_gib: 32"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "serial_console_current_tty: /dev/ttyUSB3"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "automation_admin_migration_source: x12again"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "netboot_protocol_flow: pxe-to-ipxe"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "netboot_bootfile_name: m70-forge-ipxe.efi"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "netboot_interface_name: netboot0"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/hosts.yml" "netboot_operational_bootstrap: local-esp-ipxe-chainloader"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "install_hostname: admin-sun99-forge-099070"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "freeipa_client_fqdn: admin-sun99-forge-099070.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "freeipa_client_apply_required: false"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "secure_firstboot_enrollment_expected_fqdn: admin-sun99-forge-099070.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "efi_boot_disk: /dev/sda"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "zfs_mirror_disks:"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "/dev/nvme0n1"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "/dev/nvme1n1"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "generation: c3000"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "pci_id: \"8086:19e2\""
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/admin_sun99_forge_099070.yml" "openzfs: ci_cd_required"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/all/dns_hetzner_cloud.yml" "admin-sun99-forge-099070.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/all/dns_hetzner_cloud.yml" "admin-sun99-forge.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/all/dns_hetzner_cloud.yml" "forge.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/all/dns_hetzner_cloud.yml" "forge-sun99.rfc1918.host"

assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "dest: m70-forge-ipxe.efi"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "src: /opt/gentoo-netboot/path-b/m70-forge-ipxe-172.16.99.88-ipxe.efi"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "forge-automation-admin:"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "forge-automation-admin-zfs:"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "root=ZFS=zroot/ROOT/gentoo"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "spl.spl_hostid=0x0951f603"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "bootdev=netboot0"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "ifname=netboot0:00:07:32:78:65:c6"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/group_vars/netboot_publishers.yml" "ip=172.16.99.70::172.16.99.1:255.255.255.0:admin-sun99-forge-099070:netboot0:none"

assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "admin-sun99-forge-099070.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "admin-sun99-forge.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "forge.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "forge-sun99.rfc1918.host"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "m70-forge-pxe-bootfile"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "m70-forge-ipxe.efi"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "00:07:32:78:65:C6"
assert_contains "${ANSIBLE_ROOT}/inventories/local-network/host_vars/gw_rfc99_mkccr2004_16g.yml" "172.16.99.70"
assert_contains "${ANSIBLE_ROOT}/profile-service-atoms/stage5-role-service-atoms.yml" "metal-forge-automation-admin:"
assert_contains "${ANSIBLE_ROOT}/profile-service-atoms/stage5-role-service-atoms.yml" "forge-control-plane"
assert_contains "${ANSIBLE_ROOT}/playbooks/ipa-client-live-apply.yml" "Force active kernel hostname on OpenRC live clients"
assert_contains "${ANSIBLE_ROOT}/playbooks/ipa-client-live-apply.yml" "Validate active kernel hostname"
assert_contains "${ANSIBLE_ROOT}/playbooks/ipa-client-live-apply.yml" "ipa_client_live_active_hostname.stdout | trim == ipa_client_live_short_hostname"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "/dev/sda is the EFI/iPXE boot disk only"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "/dev/nvme0n1 and /dev/nvme1n1 are the destructive mirrored ZFS targets"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "On 2026-05-14 the SATADOM boot path was backed up"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "/root/operator-private/m70/preinstall/"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "both NVMe devices were wiped"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "zroot/ROOT/gentoo"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "M70IPXE"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "Intel QAT"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "Forge Continuity Restore"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "/srv/restore/x12again-root/20260513-191801/root"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "dev-vcs/git-lfs"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "GNU Emacs 30"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "/etc/eixrc/00-eixrc"
assert_contains "docs/M70-FORGE-AUTOMATION-ADMIN.md" "Full \`/opt\` import is therefore deferred"
assert_contains "docs/INTEL-QAT-C3000-ACCELERATION.md" "OpenZFS+QAT"
assert_contains "docs/INTEL-QAT-C3000-ACCELERATION.md" "1.5x-2x TLS RPS improvements"
assert_contains "docs/ROADMAP-AND-TODO.md" "HWACC-003"
assert_contains "docs/wiki/M70-Forge-Automation-Admin.md" "both NVMe devices were wiped"
assert_contains "docs/wiki/M70-Forge-Automation-Admin.md" "zroot/ROOT/gentoo"
assert_contains "docs/wiki/M70-Forge-Automation-Admin.md" "/srv/restore/x12again-root/20260513-191801/root"
assert_contains "docs/wiki/M70-Forge-Automation-Admin.md" "GNU Emacs 30"
assert_contains "docs/wiki/M70-Forge-Automation-Admin.md" "/etc/eixrc/00-eixrc"
assert_contains "docs/wiki/M70-Forge-Automation-Admin.md" "Full \`/opt\` import is deferred"
assert_contains "docs/wiki/Intel-QAT-C3000-Acceleration.md" "OpenZFS+QAT"
assert_contains "docs/runbooks/m70-automation-admin-install.md" "M70IPXE"
assert_contains "docs/runbooks/m70-automation-admin-install.md" "root=ZFS=zroot/ROOT/gentoo"
assert_contains "docs/runbooks/m70-automation-admin-install.md" "ptmxmode=666"
assert_contains "docs/X11SCL-IF-FORGE-AUTOMATION-ADMIN.md" "Supermicro X11SCL-IF"
assert_contains "docs/X11SCL-IF-FORGE-AUTOMATION-ADMIN.md" "Intel Xeon E-2176G"
assert_contains "docs/X11SCL-IF-FORGE-AUTOMATION-ADMIN.md" "Samsung 883-DCT 2TB"
assert_contains "docs/X11SCL-IF-FORGE-AUTOMATION-ADMIN.md" "QLogic QL41234"
assert_contains "docs/X11SCL-IF-FORGE-AUTOMATION-ADMIN.md" "Do not repoint the stable Forge aliases"
assert_contains "docs/X11SCL-IF-FORGE-AUTOMATION-ADMIN.md" "metal-forge-automation-admin"
assert_contains "docs/wiki/X11SCL-IF-Forge-Automation-Admin.md" "Cutover Policy"
assert_contains "docs/wiki/README.md" "X11SCL-IF-Forge-Automation-Admin.md"
assert_contains "docs/wiki/_Sidebar.md" "X11SCL-IF Forge Automation Admin"
assert_contains "docs/runbooks/x11scl-if-forge-admin-build.md" "Do not reimage X12AGAIN"
assert_contains "docs/runbooks/x11scl-if-forge-admin-build.md" "zroot/ROOT/gentoo"
assert_contains "docs/runbooks/x11scl-if-forge-admin-build.md" "gh auth status"
assert_contains "docs/ROADMAP-AND-TODO.md" "ADM-004"
assert_contains "docs/ROADMAP-AND-TODO.md" "Promote X11SCL-IF as long-term Forge automation-admin platform"

assert_contains "tests/shell/run-tests.sh" "test_m70_forge_admin_provisioning.sh"

echo "M70 Forge automation-admin provisioning checks passed."
