#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

assert_file_contains() {
  local file="$1"
  local pattern="$2"

  [[ -f "${file}" ]] || fail "missing file ${file}"
  grep -Fq "${pattern}" "${file}" || fail "expected ${file} to contain ${pattern}"
}

canary_doc="${REPO_ROOT}/docs/M70-CANARY-VALIDATION-LANE.md"
satadom_doc="${REPO_ROOT}/docs/M70-CANARY-SATADOM-EFI-CARRIER.md"
platform_doc="${REPO_ROOT}/docs/M70-PLATFORM-OPTIMIZATION-PLAN.md"
serial_doc="${REPO_ROOT}/docs/M70-SERIAL-CONSOLE-MAP.md"
gap_doc="${REPO_ROOT}/docs/M70-CANARY-GAP-ANALYSIS-2026-05-24.md"
eod_doc="${REPO_ROOT}/docs/EOD-STATUS-2026-05-25.md"
eod_20260526_doc="${REPO_ROOT}/docs/EOD-STATUS-2026-05-26.md"
overnight_doc="${REPO_ROOT}/docs/OVERNIGHT-EXECUTION-2026-05-25.md"
wiki_canary="${REPO_ROOT}/docs/wiki/M70-Canary-Validation-Lane.md"
wiki_satadom="${REPO_ROOT}/docs/wiki/M70-Canary-SATADOM-EFI-Carrier.md"
wiki_platform="${REPO_ROOT}/docs/wiki/M70-Platform-Optimization-Plan.md"
wiki_serial="${REPO_ROOT}/docs/wiki/M70-Serial-Console-Map.md"
wiki_gap="${REPO_ROOT}/docs/wiki/M70-Canary-Gap-Analysis-2026-05-24.md"
wiki_eod="${REPO_ROOT}/docs/wiki/EOD-Status-2026-05-25.md"
wiki_eod_20260526="${REPO_ROOT}/docs/wiki/EOD-Status-2026-05-26.md"
wiki_overnight="${REPO_ROOT}/docs/wiki/Overnight-Execution-2026-05-25.md"
wiki_home="${REPO_ROOT}/docs/wiki/Home.md"
wiki_sidebar="${REPO_ROOT}/docs/wiki/_Sidebar.md"
wiki_readme="${REPO_ROOT}/docs/wiki/README.md"
diagram_dir="${REPO_ROOT}/docs/diagrams"
run_tests="${REPO_ROOT}/tests/shell/run-tests.sh"
ansible_root="${REPO_ROOT}/gentoo_stage4_llvm_split-usr_no-multilib_hardened/gentoo-liveiso-ansible"
m70_host_vars="${ansible_root}/inventories/local-network/host_vars/m70_canary.yml"
platform_profile_role="${ansible_root}/roles/platform_profile/tasks/main.yml"
preflight_role="${ansible_root}/roles/preflight/tasks/main.yml"
ansible_readme="${ansible_root}/README.md"

assert_file_contains "${canary_doc}" "Current Remediation State"
assert_file_contains "${canary_doc}" "sbsoc-accel-int64-m70n2.rfc1918.host"
assert_file_contains "${canary_doc}" "90-intel-qat-c3000.config"
assert_file_contains "${canary_doc}" "kernel/x86/microcode/AuthenticAMD.bin"
assert_file_contains "${canary_doc}" "kernel/x86/microcode/GenuineIntel.bin"
assert_file_contains "${canary_doc}" "spl_hostid=1709fd12"
assert_file_contains "${canary_doc}" "Installed-root validation on 2026-05-25"
assert_file_contains "${canary_doc}" "lacp_status: negotiated"
assert_file_contains "${canary_doc}" "SATADOM EFI carrier"
assert_file_contains "${canary_doc}" "FWS-2363"
assert_file_contains "${canary_doc}" "docs/M70-CANARY-SATADOM-EFI-CARRIER.md"
assert_file_contains "${canary_doc}" "SATADOM local boot succeeded twice"
assert_file_contains "${canary_doc}" "profile_udev_rules_files"
assert_file_contains "${canary_doc}" "DISTCC_FALLBACK=0"
assert_file_contains "${canary_doc}" "FEATURES"
assert_file_contains "${canary_doc}" "probe compile"
assert_file_contains "${canary_doc}" "FreeIPA live apply dry-run"
assert_file_contains "${canary_doc}" "svc_identity_ipa01"
assert_file_contains "${canary_doc}" "M70 To Canary Swimlane"
assert_file_contains "${canary_doc}" "m70-canary-actions-2026-05-26.svg"
assert_file_contains "${canary_doc}" "@startuml"

assert_file_contains "${satadom_doc}" "M70 Canary SATADOM EFI Carrier"
assert_file_contains "${satadom_doc}" "SATADOM removable EFI fallback -> ZFSBootMenu -> NVMe rpool/ROOT/gentoo"
assert_file_contains "${satadom_doc}" "AAA SATADOM EFI carrier write gate: existing ESP copy approved"
assert_file_contains "${satadom_doc}" "AAA SATADOM EFI carrier destructive conversion approved"
assert_file_contains "${satadom_doc}" "20180915AA9241033080"
assert_file_contains "${satadom_doc}" "ata-SATADOM-SH_3ME3_20180915AA9241033080-part1"
assert_file_contains "${satadom_doc}" "nvme-eui.8ce38e0403ef1a38"
assert_file_contains "${satadom_doc}" "ssh m70_canary"
assert_file_contains "${satadom_doc}" "Approval 1 does not imply Approval 2"
assert_file_contains "${satadom_doc}" "Boot Option #1"

assert_file_contains "${platform_doc}" "Current canary evidence from 2026-05-24"
assert_file_contains "${platform_doc}" "kernel_config"
assert_file_contains "${platform_doc}" "local ZFSBootMenu boot validation"
assert_file_contains "${serial_doc}" "m70_canary"

assert_file_contains "${gap_doc}" "Open Issue Review"
assert_file_contains "${gap_doc}" "86 open issues"
assert_file_contains "${gap_doc}" "#144"
assert_file_contains "${gap_doc}" "#160"
assert_file_contains "${gap_doc}" "#161"
assert_file_contains "${gap_doc}" "Remaining documentation gaps"
assert_file_contains "${eod_doc}" "EOD Status 2026-05-25"
assert_file_contains "${eod_doc}" "SATADOM"
assert_file_contains "${eod_doc}" "10-m70-canary-net-names.rules"
assert_file_contains "${eod_doc}" "MAKEOPTS=-j24"
assert_file_contains "${eod_doc}" "managed distcc wrapper"
assert_file_contains "${eod_doc}" "ipa-client-live-apply.yml --check --diff"
assert_file_contains "${eod_doc}" "delegated controller SSH"
assert_file_contains "${eod_20260526_doc}" "EOD Status 2026-05-26"
assert_file_contains "${eod_20260526_doc}" "Atlas focused on closing the M70 canary validation lane"
assert_file_contains "${eod_20260526_doc}" "FCP And Flat-File Reconciliation"
assert_file_contains "${eod_20260526_doc}" 'from that part of the FCP reply for `m70_canary` only'
assert_file_contains "${eod_20260526_doc}" "PlantUML Swimlane - M70 To Canary"
assert_file_contains "${eod_20260526_doc}" "PlantUML - Atlas Requirement To Actions"
assert_file_contains "${eod_20260526_doc}" "PlantUML - Atlas Observable Cognitive Workflow"
assert_file_contains "${eod_20260526_doc}" "m70-canary-actions-2026-05-26.png"
assert_file_contains "${eod_20260526_doc}" "atlas-cognitive-workflow-2026-05-26.svg"
assert_file_contains "${overnight_doc}" "Overnight Execution 2026-05-25"
assert_file_contains "${overnight_doc}" "SLURM Pilot Repo Work"
assert_file_contains "${overnight_doc}" "PR 144 / SLURM Branch Integration Gate"
assert_file_contains "${overnight_doc}" 'GitHub reports PR `#144` merge state as `DIRTY`'
assert_file_contains "${overnight_doc}" "no NetworkManager"

assert_file_contains "${wiki_canary}" "M70 Canary Validation Lane"
assert_file_contains "${wiki_satadom}" "M70 Canary SATADOM EFI Carrier"
assert_file_contains "${wiki_satadom}" "Approval 1 does not imply Approval 2"
assert_file_contains "${wiki_platform}" "M70 Platform Optimization Plan"
assert_file_contains "${wiki_serial}" "M70 Serial Console Map"
assert_file_contains "${wiki_gap}" "M70 Canary Gap Analysis 2026-05-24"
assert_file_contains "${wiki_eod}" "EOD Status 2026-05-25"
assert_file_contains "${wiki_eod_20260526}" "EOD Status 2026-05-26"
assert_file_contains "${wiki_eod_20260526}" "PlantUML Swimlane - M70 To Canary"
assert_file_contains "${wiki_eod_20260526}" "PlantUML - Atlas Requirement To Actions"
assert_file_contains "${wiki_overnight}" "Overnight Execution 2026-05-25"
assert_file_contains "${wiki_overnight}" "PR 144 / SLURM Branch Integration Gate"
assert_file_contains "${wiki_home}" "M70 Canary Validation Lane"
assert_file_contains "${wiki_home}" "M70 Canary SATADOM EFI Carrier"
assert_file_contains "${wiki_home}" "EOD Status 2026-05-26"
assert_file_contains "${wiki_home}" "EOD Status 2026-05-25"
assert_file_contains "${wiki_sidebar}" "M70 Canary Validation Lane"
assert_file_contains "${wiki_sidebar}" "M70 Canary SATADOM EFI Carrier"
assert_file_contains "${wiki_sidebar}" "EOD Status 2026-05-26"
assert_file_contains "${wiki_sidebar}" "Overnight Execution 2026-05-25"
assert_file_contains "${wiki_readme}" "M70-Canary-Validation-Lane.md"
assert_file_contains "${wiki_readme}" "M70-Canary-SATADOM-EFI-Carrier.md"
assert_file_contains "${wiki_readme}" "EOD-Status-2026-05-26.md"
assert_file_contains "${wiki_readme}" "EOD-Status-2026-05-25.md"
assert_file_contains "${diagram_dir}/m70-canary-actions-2026-05-26.puml" "M70 <-> M70 Canary Activity"
assert_file_contains "${diagram_dir}/atlas-requirement-to-actions-2026-05-26.puml" "Portage atom or dependency tree involved"
assert_file_contains "${diagram_dir}/atlas-cognitive-workflow-2026-05-26.puml" "Observable Reasoning Workflow"
[[ -s "${diagram_dir}/m70-canary-actions-2026-05-26.png" ]] || fail "missing rendered m70 canary PNG"
[[ -s "${diagram_dir}/m70-canary-actions-2026-05-26.svg" ]] || fail "missing rendered m70 canary SVG"
[[ -s "${diagram_dir}/atlas-requirement-to-actions-2026-05-26.png" ]] || fail "missing rendered Atlas action PNG"
[[ -s "${diagram_dir}/atlas-requirement-to-actions-2026-05-26.svg" ]] || fail "missing rendered Atlas action SVG"
[[ -s "${diagram_dir}/atlas-cognitive-workflow-2026-05-26.png" ]] || fail "missing rendered Atlas workflow PNG"
[[ -s "${diagram_dir}/atlas-cognitive-workflow-2026-05-26.svg" ]] || fail "missing rendered Atlas workflow SVG"
assert_file_contains "${run_tests}" "test_m70_canary_docs.sh"
assert_file_contains "${m70_host_vars}" "10-m70-canary-net-names.rules"
assert_file_contains "${m70_host_vars}" "00:07:32:58:73:34"
assert_file_contains "${platform_profile_role}" "resolved_profile_udev_rules_files"
assert_file_contains "${preflight_role}" "resolved_profile_udev_rules_files"
assert_file_contains "${ansible_readme}" "udev_rules_files"

printf 'PASS: %s\n' "$(basename "${BASH_SOURCE[0]}")"
