---
zfsbootmenu_efi_url: https://get.zfsbootmenu.org/efi
zfsbootmenu_boot_label: ZFSBootMenu
zfsbootmenu_efi_directory: /efi/EFI/ZBM
zfsbootmenu_efi_filename: VMLINUZ.EFI
zfsbootmenu_fallback_directory: /efi/EFI/BOOT
zfsbootmenu_fallback_filename: BOOTX64.EFI
zfsbootmenu_prefer: "{{ zpool_name }}/ROOT/gentoo"
zfsbootmenu_timeout: 0
zfsbootmenu_efi_commandline: >-
  zbm.prefer={{ zfsbootmenu_prefer }}
  ro
  zbm.timeout={{ zfsbootmenu_timeout }}
  console=tty0
  console=ttyS0,115200
zfsbootmenu_root_commandline: >-
  {{
    (install_kernel_cmdline | default('ro console=tty0 console=ttyS0,115200'))
    | regex_replace('(^|\\s)root=[^\\s]+', '')
    | regex_replace('\\s+', ' ')
    | trim
  }}
