---
gentoo_profile_definition:
  package_list_files:
    - profile-package-lists/cloud-init-base.packages
  cloud_init:
    enabled: true
    disable_root: false
    ssh_pwauth: false
    datasource_list:
      - NoCloud
    seedfrom: file:///var/lib/cloud/seed/nocloud-net/
