---
profile_definition_files:
  - "{{ playbook_dir }}/../profile-definitions/llvm-clang-hardened-portage.yml"
  - "{{ playbook_dir }}/../profile-definitions/hardened-llvm-stage4-merged-usr.yml"
  - "{{ playbook_dir }}/../profile-definitions/cloud-init-vm.yml"
  - "{{ playbook_dir }}/../profile-definitions/vm-guest-simple-ipxe.yml"

install_networkmanager: true
install_openssh: true
install_hostname: ipxe-test
profile_cloud_init:
  enabled: true
  instance_id: vm-guest-simple
  local_hostname: ipxe-test
  disable_root: false
  ssh_pwauth: false
