---
profile_definition_files:
  - "{{ playbook_dir }}/../profile-definitions/llvm-clang-hardened-portage.yml"
  - "{{ playbook_dir }}/../profile-definitions/hardened-llvm-stage4-merged-usr.yml"
  - "{{ playbook_dir }}/../profile-definitions/cloud-init-vm.yml"
  - "{{ playbook_dir }}/../profile-definitions/logging-rsyslog-client.yml"
  - "{{ playbook_dir }}/../profile-definitions/nfs-storage-client.yml"
  - "{{ playbook_dir }}/../profile-definitions/aaa-domain-client.yml"
  - "{{ playbook_dir }}/../profile-definitions/vm-guest-application-server.yml"
  - "{{ playbook_dir }}/../profile-definitions/vm-observability-victoriametrics.yml"

install_networkmanager: true
install_openssh: true
install_hostname: vm-observability-victoriametrics

profile_cloud_init:
  enabled: true
  instance_id: vm-observability-victoriametrics
  local_hostname: vm-observability-victoriametrics
  disable_root: false
  ssh_pwauth: false
