---
profile_definition_files:
  - "{{ playbook_dir }}/../profile-definitions/llvm-clang-hardened-portage.yml"
  - "{{ playbook_dir }}/../profile-definitions/hardened-llvm-stage4-merged-usr.yml"
  - "{{ playbook_dir }}/../profile-definitions/cloud-init-vm.yml"
  - "{{ playbook_dir }}/../profile-definitions/logging-rsyslog-client.yml"
  - "{{ playbook_dir }}/../profile-definitions/telemetry-node-exporter-client.yml"
  - "{{ playbook_dir }}/../profile-definitions/vm-guest-simple-ipxe.yml"
  - "{{ playbook_dir }}/../profile-definitions/vm-workstation-nscde.yml"
  - "{{ playbook_dir }}/../profile-definitions/vm-workstation-nscde-gpu-pikvm.yml"

install_networkmanager: true
install_openssh: true
install_hostname: vm-workstation-nscde-gpu01

profile_cloud_init:
  enabled: true
  instance_id: vm-workstation-nscde-gpu01
  local_hostname: vm-workstation-nscde-gpu01
  disable_root: false
  ssh_pwauth: false

profile_workstation_session_stack:
  display_policy:
    bus_id: PCI:1:0:0
    preferred_mode: 1280x720
