---
all:
  vars:
    ansible_python_interpreter: auto_silent
  children:
    local_management:
      children:
        proxmox_hypervisors:
        mikrotik_routeros:
        mikrotik_swos:

    proxmox_hypervisors:
      hosts:
        hasslehoff:
          ansible_host: 172.16.99.9
          ansible_user: root
          local_network_role: proxmox-hypervisor
          proxmox_api_host: 172.16.99.9
          proxmox_api_port: 8006
          proxmox_api_validate_certs: false
          proxmox_api_token_id: "{{ vault_hasslehoff_proxmox_api_token_id }}"
          proxmox_api_token_secret: "{{ vault_hasslehoff_proxmox_api_token_secret }}"

    mikrotik_routeros:
      hosts:
        sw_mgmt_mkcrs354:
          ansible_host: 172.16.99.7
          ansible_user: admin
          ansible_password: "{{ vault_crs354_admin_password }}"
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
          local_network_role: distribution-switch
          routeros_identity: sw-mgmt-mkcrs354
          routeros_model: CRS354-48G-4S+2Q+
          routeros_version_target: 7.22.2
        rtr_mgmt_ccr2004:
          ansible_host: 172.16.99.120
          ansible_user: admin
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
          local_network_role: routeros-gateway-candidate
          routeros_model: CCR2004-1G-2XS-PCIe

    mikrotik_swos:
      hosts:
        sw_mgmt_css326:
          ansible_host: 172.16.99.6
          local_network_role: access-switch
          swos_username: admin
          swos_password: "{{ vault_css326_admin_password }}"
          swos_model: CSS326-24G-2S+
