---
slurm_cluster_default_enabled: false
slurm_cluster_default_cluster_name: rfc99
slurm_cluster_default_control_machine: sched-sun99-slurmctl-099071
slurm_cluster_default_control_addr: 172.16.99.71
slurm_cluster_default_controller_enabled: false
slurm_cluster_default_dbd_enabled: false
slurm_cluster_default_worker_enabled: false
slurm_cluster_default_user: slurm
slurm_cluster_default_group: slurm
slurm_cluster_default_munge_user: munge
slurm_cluster_default_munge_group: munge
slurm_cluster_default_munge_key_b64: ""
slurm_cluster_default_state_save_location: /var/lib/slurm/slurmctld
slurm_cluster_default_slurmd_spool_dir: /var/lib/slurm/slurmd
slurm_cluster_default_log_dir: /var/log/slurm
slurm_cluster_default_config_dir: /etc/slurm
slurm_cluster_default_accounting_storage_host: 127.0.0.1
slurm_cluster_default_accounting_storage_database: slurm_acct_db
slurm_cluster_default_accounting_storage_user: slurm
slurm_cluster_default_accounting_storage_password_ref: VAULT_REQUIRED
slurm_cluster_default_nodes: []
slurm_cluster_default_node_features: []
slurm_cluster_default_partitions:
  - name: build
    default: true
    nodes: ALL
    max_time: 2-00:00:00
    state: UP
  - name: validation
    default: false
    nodes: ALL
    max_time: 12:00:00
    state: UP
  - name: gpu-test
    default: false
    nodes: ALL
    max_time: 12:00:00
    state: UP
  - name: rdma-test
    default: false
    nodes: ALL
    max_time: 12:00:00
    state: DRAIN
