#!/bin/bash
set -euo pipefail

IPA_HOST="${IPA_HOST:-172.16.99.63}"
IPA_SSH_USER="${IPA_SSH_USER:-codex}"
IPA_REALM="${IPA_REALM:-RFC1918.HOST}"
IPA_DOMAIN="${IPA_DOMAIN:-rfc1918.host}"
IPA_BASE_DN="${IPA_BASE_DN:-dc=rfc1918,dc=host}"
IDENTITY_SECRET_FILE="${IDENTITY_SECRET_FILE:-/root/operator-private/identity/ipa01.env}"
CODEX_ADMIN_PUBKEY_FILE="${CODEX_ADMIN_PUBKEY_FILE:-${HOME}/.ssh/id_ed25519.pub}"

if [[ ! -f "${IDENTITY_SECRET_FILE}" ]]; then
  echo "Missing identity secret file: ${IDENTITY_SECRET_FILE}" >&2
  exit 2
fi

if [[ ! -r "${CODEX_ADMIN_PUBKEY_FILE}" ]]; then
  echo "Missing Codex admin public key: ${CODEX_ADMIN_PUBKEY_FILE}" >&2
  exit 2
fi

append_secret_if_missing() {
  local name="$1"
  if ! grep -qE "^${name}=" "${IDENTITY_SECRET_FILE}"; then
    printf '%s=%q\n' "${name}" "$(openssl rand -base64 30)" >> "${IDENTITY_SECRET_FILE}"
    chmod 0600 "${IDENTITY_SECRET_FILE}"
  fi
}

append_secret_if_missing RADIUS_SHARED_SECRET
append_secret_if_missing RADIUS_TEST_PASSWORD

ssh_target="${IPA_SSH_USER}@${IPA_HOST}"
remote_env="/tmp/stage5-identity-bootstrap.env"
remote_pubkey="/tmp/stage5-codex-admin.pub"

scp -q "${IDENTITY_SECRET_FILE}" "${ssh_target}:${remote_env}"
scp -q "${CODEX_ADMIN_PUBKEY_FILE}" "${ssh_target}:${remote_pubkey}"
ssh -o BatchMode=yes -o ConnectTimeout=20 "${ssh_target}" \
  "sudo install -d -m 0700 /root/stage5-identity && sudo install -m 0600 ${remote_env} /root/stage5-identity/bootstrap.env && sudo install -m 0600 ${remote_pubkey} /root/stage5-identity/codex-admin.pub && rm -f ${remote_env} ${remote_pubkey}"

ssh -o BatchMode=yes -o ConnectTimeout=20 "${ssh_target}" sudo bash -s -- \
  "${IPA_REALM}" \
  "${IPA_DOMAIN}" \
  "${IPA_BASE_DN}" << 'REMOTE'
set -euo pipefail

ipa_realm="$1"
ipa_domain="$2"
ipa_base_dn="$3"

# shellcheck source=/dev/null
source /root/stage5-identity/bootstrap.env

kinit admin <<<"${IPA_ADMIN_PASSWORD}" >/dev/null

ldap_bind_dn="uid=radiusd,cn=sysaccounts,cn=etc,${ipa_base_dn}"
set +e
ldapsearch -LLL -x -D "cn=Directory Manager" -w "${IPA_DS_PASSWORD}" -b "${ldap_bind_dn}" dn >/tmp/stage5-radiusd-sysaccount.search 2>/dev/null
ldapsearch_rc=$?
set -e
if [[ "${ldapsearch_rc}" -eq 0 ]] && grep -q '^dn:' /tmp/stage5-radiusd-sysaccount.search; then
  ldapmodify -x -D "cn=Directory Manager" -w "${IPA_DS_PASSWORD}" >/dev/null <<LDIF
dn: ${ldap_bind_dn}
changetype: modify
replace: userPassword
userPassword: ${RADIUS_LDAP_PASSWORD}
LDIF
else
  ldapadd -x -D "cn=Directory Manager" -w "${IPA_DS_PASSWORD}" >/dev/null <<LDIF
dn: ${ldap_bind_dn}
objectClass: account
objectClass: simpleSecurityObject
uid: radiusd
userPassword: ${RADIUS_LDAP_PASSWORD}
description: FreeRADIUS LDAP bind account managed by Stage5 bootstrap
LDIF
fi

codex_pubkey="$(cat /root/stage5-identity/codex-admin.pub)"
if ipa user-show codex-admin >/dev/null 2>&1; then
  ipa user-mod codex-admin --sshpubkey="${codex_pubkey}" >/dev/null 2>&1 || true
else
  ipa user-add codex-admin \
    --first=Codex \
    --last=Admin \
    --shell=/bin/bash \
    --homedir=/home/codex-admin \
    --sshpubkey="${codex_pubkey}" >/dev/null
fi
ipa group-add-member linux-admin --users=codex-admin >/dev/null 2>&1 || true

if ! ipa user-show radius-test >/dev/null 2>&1; then
  ipa user-add radius-test \
    --first=Radius \
    --last=Test \
    --shell=/sbin/nologin \
    --homedir=/var/empty/radius-test >/dev/null
fi
printf '%s\n%s\n' "${RADIUS_TEST_PASSWORD}" "${RADIUS_TEST_PASSWORD}" | ipa passwd radius-test >/dev/null
ldapmodify -x -D "cn=Directory Manager" -w "${IPA_DS_PASSWORD}" >/dev/null <<LDIF
dn: uid=radius-test,cn=users,cn=accounts,${ipa_base_dn}
changetype: modify
replace: krbPasswordExpiration
krbPasswordExpiration: 20380119031407Z
LDIF
ipa group-add-member network-readonly --users=radius-test >/dev/null 2>&1 || true

install -o root -g radiusd -m 0640 /dev/null /etc/raddb/radiusd-ldap.secret
printf '%s' "${RADIUS_LDAP_PASSWORD}" >/etc/raddb/radiusd-ldap.secret
install -o root -g radiusd -m 0640 /dev/null /etc/raddb/clients.stage5.conf
cat >/etc/raddb/clients.stage5.conf <<EOF
# Generated by scripts/configure-freeradius-freeipa.sh
client stage5_local_management {
  ipaddr = 172.16.99.0/24
  secret = ${RADIUS_SHARED_SECRET}
  shortname = stage5-local-management
  nastype = other
}
EOF
chown root:radiusd /etc/raddb/clients.stage5.conf
chmod 0640 /etc/raddb/clients.stage5.conf

if ! grep -q 'clients.stage5.conf' /etc/raddb/clients.conf; then
  cp -a /etc/raddb/clients.conf "/etc/raddb/clients.conf.stage5.$(date +%Y%m%d%H%M%S).bak"
  printf '\n$INCLUDE clients.stage5.conf\n' >>/etc/raddb/clients.conf
fi

cp -a /etc/raddb/mods-available/ldap "/etc/raddb/mods-available/ldap.stage5.$(date +%Y%m%d%H%M%S).bak"
cat >/etc/raddb/mods-available/ldap <<EOF
# Generated by scripts/configure-freeradius-freeipa.sh
ldap {
  server = '127.0.0.1'
  port = 389
  identity = '${ldap_bind_dn}'
  password = '${RADIUS_LDAP_PASSWORD}'
  base_dn = '${ipa_base_dn}'
  user {
    base_dn = "cn=users,cn=accounts,\${..base_dn}"
    filter = "(uid=%{%{Stripped-User-Name}:-%{User-Name}})"
  }
  group {
    base_dn = "cn=groups,cn=accounts,\${..base_dn}"
    filter = "(|(member=%{control:LDAP-UserDn})(memberUid=%{%{Stripped-User-Name}:-%{User-Name}}))"
    name_attribute = cn
  }
  profile {
  }
  options {
    chase_referrals = yes
    rebind = yes
    res_timeout = 10
    srv_timelimit = 10
    net_timeout = 1
    idle = 60
    probes = 3
    interval = 3
  }
  tls {
    start_tls = no
    require_cert = 'never'
  }
  pool {
    start = 5
    min = 3
    max = 32
    spare = 10
    uses = 0
    retry_delay = 30
    lifetime = 0
    idle_timeout = 60
  }
}
EOF
chown root:radiusd /etc/raddb/mods-available/ldap
chmod 0640 /etc/raddb/mods-available/ldap
ln -sfn ../mods-available/ldap /etc/raddb/mods-enabled/ldap

cp -a /etc/raddb/sites-available/default "/etc/raddb/sites-available/default.stage5.$(date +%Y%m%d%H%M%S).bak"
python3 - <<'PY'
from pathlib import Path
import re

path = Path("/etc/raddb/sites-available/default")
text = path.read_text()
text = text.replace("\n\t-ldap\n", "\n\tldap\n")
text = re.sub(
    r"\n#\tif \(\(ok \|\| updated\) && User-Password && !control:Auth-Type\) \{\n#\t\tupdate control \{\n#\t\t\t&Auth-Type := ldap\n#\t\t\}\n#\t\}\n",
    "\n\tif ((ok || updated) && User-Password && !control:Auth-Type) {\n\t\tupdate control {\n\t\t\t&Auth-Type := ldap\n\t\t}\n\t}\n",
    text,
)
text = re.sub(
    r"\n#\tAuth-Type LDAP \{\n#\t\tldap\n#\t\}\n",
    "\n\tAuth-Type LDAP {\n\t\tldap\n\t}\n",
    text,
)
path.write_text(text)
PY
chown root:radiusd /etc/raddb/sites-available/default
chmod 0640 /etc/raddb/sites-available/default

if [[ -x /etc/raddb/certs/bootstrap && ! -f /etc/raddb/certs/server.pem ]]; then
  (cd /etc/raddb/certs && ./bootstrap) >/root/stage5-identity/freeradius-certs-bootstrap.log 2>&1
  chown root:radiusd /etc/raddb/certs/* || true
fi

radiusd -XC -d /etc/raddb >/root/stage5-identity/radiusd-config-check.log 2>&1
systemctl enable --now radiusd.service >/dev/null
systemctl restart radiusd.service

set +e
radtest radius-test "${RADIUS_TEST_PASSWORD}" 127.0.0.1 0 testing123 >/root/stage5-identity/radtest.log 2>&1
radtest_rc=$?
set -e
if [[ "${radtest_rc}" -ne 0 ]] || ! grep -q 'Access-Accept' /root/stage5-identity/radtest.log; then
  sed -E 's/User-Password = ".*"/User-Password = "[redacted]"/' /root/stage5-identity/radtest.log >&2
  exit 1
fi

install -d -m 0755 /etc/stage5-identity
cat >/etc/stage5-identity/freeradius-freeipa.yml <<EOF
realm: ${ipa_realm}
domain: ${ipa_domain}
base_dn: ${ipa_base_dn}
ldap_bind_dn: ${ldap_bind_dn}
radius_auth_port: 1812
radius_acct_port: 1813
local_management_client: 172.16.99.0/24
validated_radtest_user: radius-test
EOF

echo "FreeRADIUS FreeIPA bridge validated for ${ipa_domain}"
REMOTE
