---
all:
  vars:
    ansible_python_interpreter: auto_silent
  children:
    fmt2_openstack_kolla:
      children:
        fmt2_kolla_deployers:
        fmt2_kolla_controllers:
        fmt2_kolla_network:
        fmt2_kolla_compute:
        fmt2_kolla_storage_anchors:

    fmt2_kolla_deployers:
      hosts:
        ops_fmt2_kolla_deployer_9928:
          ansible_host: 10.200.99.28
          ansible_user: verwalterin
          ansible_become: true
          fqdn: ops-fmt2-kolla-deployer-9928.rfc1918.host
          kolla_inventory_name: localhost
          local_network_role: fmt2-kolla-deployer
          stage5_profile: vm-rocky10-kolla-deployer
          parent_host: kvm_sfo200_ter_9924
          parent_storage_dataset: dstore/libvirt/images

    fmt2_kolla_controllers:
      hosts:
        kvm_sfo200_pri_9922:
          ansible_host: 10.200.99.22
          ansible_user: verwalterin
          ansible_become: true
          fqdn: kvm-sfo200-pri-9922.rfc1918.host
          kolla_inventory_name: kvm-sfo200-pri-9922
          local_network_role: fmt2-kolla-controller-network-compute
          target_os: Rocky Linux 10
          fmt2_kolla_sol_evidence_state: enabled
          fmt2_kolla_candidate_os_devices:
            - SSDSCKKB240G8R-os-mirror-a
            - SSDSCKKB240G8R-os-mirror-b

    fmt2_kolla_network:
      hosts:
        kvm_sfo200_pri_9922:

    fmt2_kolla_compute:
      hosts:
        kvm_sfo200_pri_9922:
        kvm_sfo200_sec_9923:
          ansible_host: 10.200.99.23
          ansible_user: verwalterin
          ansible_become: true
          fqdn: kvm-sfo200-sec-9923.rfc1918.host
          kolla_inventory_name: kvm-sfo200-sec-9923
          local_network_role: fmt2-kolla-compute-positive-control
          target_os: Rocky Linux 10
          fmt2_kolla_sol_evidence_state: enabled
          fmt2_kolla_candidate_os_devices:
            - SSDSCKKB240G8R-os-mirror-a
            - SSDSCKKB240G8R-os-mirror-b

    fmt2_kolla_storage_anchors:
      hosts:
        kvm_sfo200_ter_9924:
          ansible_host: 10.200.99.24
          ansible_user: verwalterin
          ansible_become: true
          fqdn: kvm-sfo200-ter-9924.rfc1918.host
          local_network_role: fmt2-kolla-storage-provisioning-anchor
          preserve_storage_pool: dstore
          dstore_images_path: /srv/libvirt/images
